# challenges.yml
# Supported rules:
# - highest_points
# - lowest_points
# - biggest_blowout
# - closest_win
# - most_points_on_bench
# - highest_pos_points:<QB|RB|WR|TE|K|D/ST>

challenges:
  - week: 1
    name: Highest Weekly Score
    rule: highest_points

  - week: 2
    name: Lowest Weekly Score (a.k.a. The Paper Bag)
    rule: lowest_points

  - week: 3
    name: Biggest Blowout
    rule: biggest_blowout

  - week: 4
    name: Closest Win
    rule: closest_win

  - week: 5
    name: Most Points Left on Bench
    rule: most_points_on_bench

  - week: 6
    name: Highest-Scoring RB
    rule: highest_pos_points:RB

  - week: 7
    name: Highest-Scoring WR
    rule: highest_pos_points:WR

  - week: 8
    name: Highest-Scoring QB
    rule: highest_pos_points:QB

  - week: 9
    name: Highest-Scoring TE
    rule: highest_pos_points:TE

  - week: 10
    name: Highest Weekly Score
    rule: highest_points

  - week: 11
    name: Biggest Blowout
    rule: biggest_blowout

  - week: 12
    name: Most Points Left on Bench
    rule: most_points_on_bench

  - week: 13
    name: Highest-Scoring FLEX (use RB/WR/TE)
    rule: highest_pos_points:RB|WR|TE

  - week: 14
    name: Highest Weekly Score
    rule: highest_points
