name: Fantasy Weekly Email
run-name: "Fantasy Week ${{ inputs.week || 'N/A' }} • ${{ github.ref_name }}"
on:
  workflow_dispatch:
    inputs:
      week:
        description: "NFL/Fantasy Week number"
        required: true
        default: "1"
      mode:
        description: "'draft' to create Gmail draft, 'send' to send"
        required: true
        default: "draft"
  schedule:
    - cron: "0 15 * * 1"  # Mondays ~9am America/Denver

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
      ESPN_S2: ${{ secrets.ESPN_S2 }}
      SWID: ${{ secrets.SWID }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}
      WEEK: ${{ inputs.week }}
      SEND_MODE: ${{ inputs.mode }}

      # --- Logo settings (pick ONE of the two blocks below) ---

      # Option A: Build from repo/branch + path (works across branches)
      LOGO_PATH: assets/genosmith.PNG
      HEADER_IMG_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/${{ env.LOGO_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug header image URL
        run: |
          set -euo pipefail
          echo "HEADER_IMG_URL='${HEADER_IMG_URL:-<empty>}'"
          curl -I --fail "$HEADER_IMG_URL"

      - name: Compose email
        run: python .github/workflows/compose_email.py
