name: Fantasy Weekly Email

on:
  workflow_dispatch:
    inputs:
      week:
        description: "NFL/Fantasy Week number"
        required: true
        default: "1"
      mode:
        description: "'draft' to create Gmail draft, 'send' to send"
        required: true
        default: "draft"
  schedule:
    - cron: "0 15 * * 1"  # Mondays ~9am America/Denver (MDT)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
      ESPN_S2: ${{ secrets.ESPN_S2 }}
      SWID: ${{ secrets.SWID }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}
      WEEK: ${{ inputs.week }}
      SEND_MODE: ${{ inputs.mode }}
      SEASON: "2025"  # <— add this for now so season is explicit

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Preflight – check env and Python
        run: |
          python --version
          echo "LEAGUE_ID=${{ secrets.LEAGUE_ID && 'present' || 'MISSING' }}"
          echo "ESPN_S2=${{ secrets.ESPN_S2 && 'present' || 'MISSING' }}"
          echo "SWID=${{ secrets.SWID && 'present' || 'MISSING (include curly braces {})' }}"
          echo "FROM_EMAIL=${{ secrets.FROM_EMAIL && 'present' || 'MISSING' }}"
          echo "GMAIL_CLIENT_ID=${{ secrets.GMAIL_CLIENT_ID && 'present' || 'MISSING' }}"
          echo "GMAIL_CLIENT_SECRET=${{ secrets.GMAIL_CLIENT_SECRET && 'present' || 'MISSING' }}"
          echo "GMAIL_REFRESH_TOKEN=${{ secrets.GMAIL_REFRESH_TOKEN && 'present' || 'MISSING' }}"
          echo "RECIPIENTS=${{ secrets.RECIPIENTS && 'present' || 'empty (ok)'}}"

      - name: Compose email from ESPN
        run: python compose_email.py

      - name: Create Draft or Send
        run: python gmail_send.py

      - name: Upload artifacts (debug)
        if: ${{ hashFiles('out/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: email-preview
          path: out/
