name: Fantasy Weekly Email

on:
  workflow_dispatch:
    inputs:
      week:
        description: "NFL/Fantasy Week number"
        required: true
        default: "1"
      mode:
        description: "'draft' to create Gmail draft, 'send' to send"
        required: true
        default: "draft"
  schedule:
    - cron: "0 15 * * 1"  # Mondays ~9am America/Denver

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
      ESPN_S2: ${{ secrets.ESPN_S2 }}
      SWID: ${{ secrets.SWID }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}
      WEEK: ${{ inputs.week }}
      SEND_MODE: ${{ inputs.mode }}
      HEADER_IMG_URL: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/assets/genosmith.PNG"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug header image URL
        run: |
          set -euo pipefail
          echo "HEADER_IMG_URL='${HEADER_IMG_URL:-<empty>}'"
          curl -I --fail "${HEADER_IMG_URL:?HEADER_IMG_URL is empty}"

      - name: Compose email
        run: python .github/workflows/compose_email.py

        - uses: actions/setup-python@v5
          with: { python-version: "3.11" }
        - run: pip install requests
        - name: Create Gmail draft (or send)
          run: python .github/workflows/send_gmail.py
